Create mockup
CodeCafeCommunity/codecafecommunity.github.io pull request #30
Opened 2024-12-28 19:20 UTC by Cykotech

## What issue is this solving?

Closes #28 

### Description

Created a simple mockup to begin a design for a home page and establish the theme of the community site. Everything is self contained in the new mockup directory.

I wasn't super picky just wanted to get quick concept on the web page. I leaned a little bit more into using the colors from the Discord logo a bit to experiment. I think a lot of things will be easier to fine tune when we implement the color scheme in Tailwind or even use HSL over hex colors.

## Any helpful knowledge/context for the reviewer?

![image](https://github.com/user-attachments/assets/23f804be-2d5b-4efc-badc-0285fabe2337)
![image](https://github.com/user-attachments/assets/c95507d1-c423-40aa-90b7-8a87eaaec0b1)

### Feelings gif (optional)

![alt text](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExc2RmNjd3czByZDl1eTB0NzZ2aHZwdW8xcWczaHB6dm53d3p2YXV0cCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/xT39D7GQo1m3LatZyU/giphy.gif)

### Please make sure you've attempted to meet the following coding standards

- [ ] ~~Code has been tested and does not produce errors~~
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code

2024-12-28 19:26 UTC, Cykotech commented
The empty span in the header is for the purpose of me not feeling like screwing around with centering the navbar and I felt as if there could be some user avatar there potentially.

2024-12-28 21:38 UTC, Jamesllllllllll commented
- Converted @Cykotech's mockup to React components & tailwind classes.
- Needs to be adapted to a Layout/Children pattern

2024-12-28 21:56 UTC, Jamesllllllllll commented
Layout implemented!

2024-12-28 21:59 UTC, lyallstewart requested changes
Nice - let's hold off merging the code changes for the time until we've had more pairs of eyes on the design though 😄

2024-12-28 22:01 UTC, Jamesllllllllll commented
> Nice - let's hold off merging the code changes for the time until we've had more pairs of eyes on the design though 😄

Yes! I think the colour scheme can be improved.

2024-12-30 04:37 UTC, aedwardg commented
I love the enthusiasm, and I think this is a great start!
That said, I don't think this PR is (or was ever intended to be) merge-able.

In the future, let's try to keep experiments like this in Draft PRs, and spin up additional branches with changes if we want to build off each others' ideas

2024-12-30 19:55 UTC, Jamesllllllllll commented
> In the future, let's try to keep experiments like this in Draft PRs, and spin up additional branches with changes if we want to build off each others' ideas

Thanks for that tip! I didn't think about branching off a branch. My enthusiasm ran away with me 😂

2024-12-30 22:54 UTC, aedwardg commented
> > In the future, let's try to keep experiments like this in Draft PRs, and spin up additional branches with changes if we want to build off each others' ideas
> 
> Thanks for that tip! I didn't think about branching off a branch. My enthusiasm ran away with me 😂 
> 

All good! Better to have people excited for a project than lack luser! :smile:

2025-01-16 05:26 UTC, merged